set(CTEST_BUILD_NAME Windows)

set(CTEST_CMAKE_GENERATOR "Visual Studio 16 2019")
set(CTEST_CMAKE_GENERATOR_PLATFORM x64)

set(
    OPTIONS
    -DCheckTypeAlign_DEVELOPER_MODE=1
    -DCMAKE_C_FLAGS=/wd5105
    -DCMAKE_CXX_FLAGS=/wd5105
)
