name: Continuous Integration

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Test
      shell: pwsh
      run: ctest
        -S ".github/ctest/$("${{ matrix.os }}".split("-")[0]).cmake"
        -VV
