name: Continuous Integration

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: ctest -S .github/ctest/ci.cmake -VV -Drunner=${{ matrix.os }}
